### ISSUE TITLE
Doesn't work with Objective-C

### ISSUE THREAD

**Issue by Dschee** [UrbanApps/Armchair#14]
I just tried different approaches to get Armchair running in an Objective-C project but I wasn't successful. Please either add instructions on how to get Armchair running in Objective-C projects or add a clear statement that Armchair only supports Swift projects in the requirements of the README.

**Comment by JensDee** [comment]
In theory you can use it from Objective C, however Armchair uses global variables (appID) and top level functions. These Swift-only features are not available in Objective C.
AFAICT, a refactoring of Armchair would be required in order to use it from Objective C. (In general it's not advisable to use global variables.)

**Comment by coneybeare** [comment]
If you want to use objective-c, you should use our [UAAppReviewManager](https://github.com/UrbanApps/UAAppReviewManager) instead.
