### ISSUE TITLE
Update code for Review From App using StoreKit (iOS >= 10.3)

### ISSUE THREAD

**Issue by hardik99** [UrbanApps/Armchair#99]
Hey ,

Update repository for review using StoreKit added by Apple from iOS >= 10.3

`SKStoreReviewController.requestReview()`

**Comment by perteraul** [comment]
+1 on this. It would be awesome.

**Comment by perteraul** [comment]
@hardik99 

I needed this, so I tweaked the Armchair.swift file in order to create a workaround. Here's what works for me, though I'm not sure it's the best practice out there and if it'll work for you. 

http://snpy.in/OkQpZF

In the `rateApp()` function I changed the current `if #available(iOS 10.3, *)` into `else if #available(iOS 10.2, *)` and added a new `		if #available(iOS 10.3, *) {
			SKStoreReviewController.requestReview()
		}` before the iOS 10.2.

**Comment by ArturoLee** [comment]
@perteraul Nice work. I thought it was weird this library didn't have that. Can you do a pull request?

**Comment by ari3l** [comment]
[This is already implemented](https://github.com/UrbanApps/Armchair/pull/92)

To use the new iOS 10.3 prompt simply do:
`Armchair.useStoreKitReviewPrompt(true)`

Perhaps this should be added to the docs.

**Comment by ArturoLee** [comment]
@ari3l You're right. This issue should be closed. And documentation would be helpful

**Comment by hardik99** [comment]
Great. It will be very helpful. 
Thanks.
